# Container name is IMPORTANT. 
# It is used in the vite.config.js file to proxy the requests to the backend and other services.
# If you change the container name, you need to update the vite.config.js file as well.
# redisinsight and pgadmin are optional. You can remove them if you don't need them.
services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_FMP_API_URL: http://127.0.0.1:8000/api
    container_name: fmp-frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - my_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: fmp-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_network
    restart: unless-stopped
  z3:
    build:
      context: ./z3-api
      dockerfile: Dockerfile
    container_name: fmp-z3-api
    environment:
      API_URL: http://fmp-backend:8000/
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - my_network
  

  dolmen-lsp:
    image: ghcr.io/soaibsafi/dolmen-lsp-proxy:0.0.1
    platform: linux/amd64
    container_name: fmp-dolmen-lsp-api
    ports:
      - "8003:8003"
    networks:
      - my_network
    restart: unless-stopped

  redis:
    image: redis:alpine
    platform: linux/amd64
    container_name: fmp-redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  pgadmin_data:
  postgres_data: