name: 🐞 Bug Report
description: File a bug/issue and help us improve FM Playground
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: 'Thank you for filing a bug report! 🐛'
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you expected to see! Be as descriptive as you can and include screenshots/permalink(s) if applicable.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      value: '1. '
    validations:
      required: false
  - type: markdown
    attributes:
      value: '## Environment'
  - type: dropdown
    id: tools
    attributes:
      label: Which tool is this issue related to?
      options:
        - Not sure
        - Limboole
        - SMT/Z3
        - Alloy
        - nuXmv
        - Spectra
    validations:
      required: true
  - type: dropdown
    id: client-os
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other (list in "Additional Notes" box)
    validations:
      required: true
  - type: dropdown
    id: desktop-browsers
    attributes:
      label: If the issue is being seen in the UI, what browsers are you seeing the problem on?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Firefox for Mobile
        - Chrome for Mobile
        - Safari on iOS
        - Other (list in "Additional Notes" box)
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
      placeholder: 'e.g. I have tried X, Y, and Z.'