services:
  z3:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: z3
    ports:
      - "8080:8080"
    environment:
      API_URL: https://play.formal-methods.net/
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
