import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices, type PartialLangiumSharedServices } from 'langium/lsp';
import { AlloyGeneratedModule, AlloyGeneratedSharedModule } from './generated/module.js';
import { AlloyUsageValidator } from './validation/alloy-usage-validator.js';
import { AlloyNameValidator } from './validation/alloy-name-validator.js';
import { registerValidationChecks } from './alloy-validator.js';
import { AlloyCompletionProvider } from './alloy-completion-provider.js';
import { AlloyScopeProvider } from './alloy-scope-provider.js';
import { AlloyWorkspaceManager } from './alloy-workspace-manager.js';
import { AlloyScopeComputation } from './alloy-scope-computation.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AlloyAddedServices = {
    validation: {
        AlloyUsageValidator: AlloyUsageValidator,
        AlloyNameValidator: AlloyNameValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AlloyServices = LangiumServices & AlloyAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AlloyLanguageModule: Module<AlloyServices, PartialLangiumServices & AlloyAddedServices> = {
    validation: {
        AlloyUsageValidator: (services) => new AlloyUsageValidator(services),
        AlloyNameValidator: (services) => new AlloyNameValidator(services)
    },
    references: {
        ScopeProvider: (services) => new AlloyScopeProvider(services),
        ScopeComputation: (services) => new AlloyScopeComputation(services)
    },
    lsp: {
        CompletionProvider: (services) => new AlloyCompletionProvider(services)
    }
};

/**
 * Shared module that overrides the default WorkspaceManager to auto-load
 * Alloy standard library modules (util/ordering, util/boolean, etc.).
 */
export const AlloySharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    workspace: {
        WorkspaceManager: (services) => new AlloyWorkspaceManager(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging three modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *  - Custom shared services (AlloySharedModule) with standard library loading
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAlloyServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Alloy: AlloyServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AlloyGeneratedSharedModule,
        AlloySharedModule
    );
    const Alloy = inject(
        createDefaultModule({ shared }),
        AlloyGeneratedModule,
        AlloyLanguageModule
    );
    shared.ServiceRegistry.register(Alloy);
    registerValidationChecks(Alloy);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Alloy };
}
